### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by MiChAeLoKGB** [jbrooksuk/InsertNums#13]
Hi, I have a little issue with key binding. Its set as default to CTRL+ALT+N but it works even without CTRL so whenever Im trying to insert } its enables the plugin. 
So I changed the key bind to CTRL+ALT+I (still works witout ctrl) as that combo does nothing.

Could you please take a look at why it works even without ctrl ?

**Comment by jbrooksuk** [comment]
Are you still experiencing this issue @MiChAeLoKGB?

**Comment by MiChAeLoKGB** [comment]
I stopped using this plugin completly, so cant really tell you if its still happening.

**Comment by jbrooksuk** [comment]
No problem. Will close as I've not had any other reports and my colleagues are using it on Windows just fine.
