### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by FichteFoll** [jbrooksuk/InsertNums#20]
@jbrooksuk 
I just noticed (while recommending this package) that there is no license in this repository. We should definitely add one.

Since I authored [all the currently used code](https://github.com/jbrooksuk/InsertNums/blame/90665efcaa57bf12c7587e36bc9e198a8247f2fb/InsertNums.py), I would like to request the MIT license being used with us both as copyright holders.

I'll go ahead with that if you agree, or you can do it yourself.
In the process, I'd also add myself to the author list reported on packagecontrol.io.

**Comment by jbrooksuk** [comment]
MIT is perfect.

**Comment by FichteFoll** [comment]
That was fast!

I'll do this next week then.

**Comment by FichteFoll** [comment]
eccf3af28169aeaa837bda9b3efbb2113663f8b8
