### ISSUE TITLE
Unexpected behavior with expression insert

### ISSUE THREAD

**Issue by z3to** [jbrooksuk/InsertNums#23]
Hopefully this project is still alive. I’m using this tool regularly.

I would expect `2:1::i*2` to result in
```
4
6
8
10
12
```

Instead I get
```
0
2
4
6
8
```

It seems like it ignores the part before the expression and uses `0:1::i*2` instead. Is this on purpose or am I missing something?

It might also be useful for others to add `::i%5` to the examples to show repeating sequences.

Thanks so much!

**Comment by FichteFoll** [comment]
`i` is the 0-based index of the loop iteration. You want `_` instead, i.e. `2:1::_*2`
