### ISSUE TITLE
New tag required for Package Control update

### ISSUE THREAD

**Issue by jpcirrus** [jbrooksuk/InsertNums#25]
The current tag is 2.0.1 dated 2014-05-02. Please could you add a new tag so Package Control knows about the changes since then. Thanks.

**Comment by FichteFoll** [comment]
Well, there haven't been a lot of changes since then since the package is basically feature complete, although I do have some. plans for improvements that I don't seem to get to.

I have a note to create a new tag for the latest change from #24, though.

**Comment by jpcirrus** [comment]
Thanks, that was the change I was looking for. Have installed manually until you do.

**Comment by FichteFoll** [comment]
https://github.com/jbrooksuk/InsertNums/releases/tag/2.0.2
